### ISSUE TITLE
Do you plan to use NotRetrofit to implement?

### ISSUE THREAD

**Issue by yongjhih** [AKiniyalocts/imgur-api#19]

**Comment by AKiniyalocts** [comment]
Currently using Retrofit 1.9 as it is listed <a href="https://github.com/square/retrofit">here</a> as the latest stable release. If Retrofit 2.0 is released, we'll update.

**Comment by yongjhih** [comment]
Sorry. I meant https://github.com/yongjhih/retrofit2. It's just a extension for retrofit now, and I'm testing it. Your project is beginning, so I think i can get some feedbacks from you.

**Comment by AKiniyalocts** [comment]
Oh neat! I'll look into it!

**Comment by JakeWharton** [comment]
FYI That project is not Retrofit 2. It's just someone's fork that they've done a bit of work on and are making false claims to the major version bump.

**Comment by chrjsorg** [comment]
We recognized that. Thanks for the info. Keep up the good work. :)
