### ISSUE TITLE
Create REST client interface

### ISSUE THREAD

**Issue by AKiniyalocts** [AKiniyalocts/imgur-api#3]
Retrofit

**Comment by chrjsorg** [comment]
I can start with some API Implementations of the /Album/ api for example. What do you think?

**Comment by AKiniyalocts** [comment]
@chrjsorg go for it. Feel free to ping me if you have any questions, I'm pretty familiar with the API.
And I'm easy to find on Google Hangouts!

**Comment by AKiniyalocts** [comment]
@chrjsorg added you as a collaborator and assigned you to this issue. Don't worry I'll be helping as well! :+1:

**Comment by chrjsorg** [comment]
We should split the issues in seperate ones

**Comment by AKiniyalocts** [comment]
Good call.
